spring:
  datasource:
    url: jdbc:mysql://work-mysql:3306/work_user_centre
  redis:
    database: 1
    host: work-redis
  cloud:
    sentinel:
      transport:
        port: 8721
        dashboard: work-sentinel:8131
server:
  address: 0.0.0.0
