spring:
  datasource:
    url: jdbc:mysql://work-mysql:3306/work_user_centre
  redis:
    database: 1
    host: work-redis
  cloud:
    sentinel:
      transport:
        port: 8721
        dashboard: work-sentinel:8131
  elasticsearch:
    uris: http://work-elasticsearch:9200
server:
  address: 0.0.0.0
nacos:
  config:
    server-addr: work-nacos:8848
dubbo:
  registry:
    address: nacos://work-nacos:8848?username=nacos&password=Qwe54188_

