spring:
  application:
    name: work-user-centre

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver # "com.mysql.jdbc.Driver" 已经过时
    url: jdbc:mysql://localhost:3306/work_user_centre
    username: work_uc
    password: 123456
  session:
    timeout: 86400 # 一天就失效

server:
  port: 8000

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted # 指定数据库全局逻辑删除字段名, 并且给实体类的对应字段加上 @TableLogic
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值
