# 配置框架
# 使用 java -jar app.jar --spring.profiles.active=develop | release | production 来启动项目, 其中 release 有时间就拿来测试, 而 production 存储在 Github 上, 每次修改 Github 配置就需要刷新(这个有时间可以优化为无需重启)
spring:
  ## 环境配置
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:develop} # 默认启动开发环境
